### ISSUE TITLE
Reveal cart on mobile when not using Storefront

### ISSUE THREAD

**Issue by jameskoster** [jameskoster/woocommerce-cart-tab#37]

**Comment by JamesJosephFinn** [comment]
I'm happily using storefront, but I'm not using the handheld footer bar, so I'm experimenting having this tab on mobile screens by implementing the following override declaration:

``` css
.woocommerce-cart-tab-container {
    display: block!important;
}
```
